require 'user.options'
require 'user.plugins'
require 'user.keymaps'
require 'user.theme'

require 'user.alpha'
require 'user.hop'
require 'user.cmp'
require 'user.autopairs'
require 'user.lualine'
require 'user.luasnip'
require 'user.neoscroll'
require 'user.treesitter'
require 'user.telescope'
require 'user.which-key'
require 'user.neo-tree'
require 'user.gitsigns'
require 'user.surround'
require 'user.indent'

require 'user.comment'
require 'user.lsp'
require 'user.languages'
